### ISSUE TITLE
:sparkles: Parent report

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app-backend#597] opened 2019-12-31 22:25 UTC
This issue accidentally got moved to the mindlogger-app repo:

https://github.com/ChildMindInstitute/mindlogger-app/issues/449

**Comment by shnizzedy** [comment] 2020-01-13 15:18
Duplicate of https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/233

**Closed by shnizzedy** 2020-01-13 15:18 UTC
Labels: mindloggerappbackend
