### ISSUE TITLE
:sparkles: Data responses: GET /applet/{id}/data

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-app-backend#599] opened 2019-12-31 22:27 UTC
This issue accidentally got moved to the mindlogger-app repo:

https://github.com/ChildMindInstitute/mindlogger-app/issues/424

**Comment by shnizzedy** [comment] 2020-01-10 20:48
duplicate of https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/256

**Closed by shnizzedy** 2020-01-10 20:48 UTC
Labels: mindloggerappbackend
